# Generated by Django 3.2.4 on 2021-07-24 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='Full name')),
                ('short_description', models.CharField(max_length=300, verbose_name='Short Description')),
                ('description', models.TextField(default='Your your details....', verbose_name='description')),
                ('image', models.ImageField(default='profile/avatar.png', upload_to=profiles.models.ProfileAvatarUploadPathGenerate, verbose_name='Image')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Custom', 'Custom'), ('Third gender', 'Third gender')], max_length=20, verbose_name='Gander')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
