# Generated by Django 3.2.5 on 2021-08-01 22:30

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to=profiles.models.ProfileAvatarUploadPathGenerate, verbose_name='Image'),
        ),
    ]
