# Generated by Django 3.2.5 on 2021-07-18 14:51

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default='Your your details....', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile/avatar.png', upload_to=profiles.models.ProfileAvatarUploadPathGenerate, verbose_name='Image'),
        ),
    ]
