# Generated by Django 3.2.5 on 2021-07-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210727_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=80, unique=True, verbose_name='slug'),
        ),
    ]
