# Generated by Django 3.2.4 on 2021-07-24 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(choices=[('Facebook', 'fa-facebook-square'), ('LinkedIn', 'fa-linkedin'), ('Twitter', 'fa-twitter-square'), ('YouTube', 'fa-youtube'), ('Pinterest', 'fa-pinterest-square'), ('Instagram', 'fa-instagram'), ('Reddit', 'fa-reddit'), ('Quora', 'fa-quora'), ('WhatsApp', 'fa-whatsapp'), ('Medium', 'fa-medium'), ('TikTok', 'fa-tiktok')], max_length=20, verbose_name='social name')),
                ('social_link', models.CharField(max_length=350, verbose_name='Social Link')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Profile')),
            ],
        ),
    ]
